[project]
name = "gto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["mypy[dmypy]>=1.18.2", "pydantic>=2.12.4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["mypy_potato", "src"]

[tool.mypy]
files = ["./src"]
plugins = ["mypy_potato"]
mypy_path = "$MYPY_CONFIG_FILE_DIR"
